module.exports = {
    URL_ALREADY_CREATED_FOR_YOU: 'URL_ALREADY_CREATED_FOR_YOU',
    URL_NOT_EXISTED: 'URL_NOT_EXISTED',
    SHORT_URL_NOT_FOUND: 'SHORT_URL_NOT_FOUND',
    SHORT_URL_NOT_EXITED_FOR_USER_ID: 'SHORT_URL_NOT_EXITED_FOR_USER_ID',
};
