module.exports = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_NAME_ALREADY_TAKEN: 'USER_NAME_ALREADY_TAKEN',
    INCORRECT_USER_NAME_OR_PASSWORD: 'INCORRECT_USER_NAME_OR_PASSWORD',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
};
