module.exports = {
    EXPIRED_TOKEN: 'EXPIRED_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    INVALID_DATA: 'INVALID_DATA',
    INVALID_EMAIL: 'INVALID_EMAIL',
    MISSING_FIELD: 'MISSING_FIELD',
    INVALID_URL: 'INVALID_URL',
    INVALID_URL_DOMAIN: 'INVALID_URL_DOMAIN',
    NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
};
